// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Thu, 26 May 2016 14:04:46 GMT

using System.Reflection;

[assembly: AssemblyVersion("2.14.19626.0")]
[assembly: AssemblyFileVersion("2.14.19626.1404")]
