// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Thu, 21 May 2015 09:01:42 GMT

using System.Reflection;

[assembly: AssemblyVersion("2.14.18421.0")]
[assembly: AssemblyFileVersion("2.14.18421.901")]
