// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Thu, 24 Sep 2015 16:32:30 GMT

using System.Reflection;

[assembly: AssemblyVersion("2.14.18824.0")]
[assembly: AssemblyFileVersion("2.14.18824.1632")]
